version: '3'
services:

  book_catalog:
    image: book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - DATABASE_URL=postgresql://sit722_part3_i7wo_user:HO7F1jE4yrrQZV3N5nTz4ajhpkg9J5wR@dpg-crfrr7qj1k6c7397jah0-a.oregon-postgres.render.com/sit722_part3_i7wo
    restart: "no"

  inventory_management:
    image: inventory_management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
     - "4002:80"
    environment:
      - PORT=80
      - DATABASE_URL=postgresql://sit722_part3_i7wo_user:HO7F1jE4yrrQZV3N5nTz4ajhpkg9J5wR@dpg-crfrr7qj1k6c7397jah0-a.oregon-postgres.render.com/sit722_part3_i7wo
    restart: "no"
 